URL_TO_MONITOR=['www.skipq.org','www.fiverr.com']
#URL_TO_MONITOR='www.skipq.org'
Namespace='AbdulBasit_webheathlambdametrics'
matric_name_avalibality='URL_Avalibality'
matric_name_latancy='URL_latency'
CloudWach='CloudWatchFullAccess'
Dynamodbpolicy="AmazonDynamoDBFullAccess"
Threshold_Avalibality=1
Threshold_latency=0.25
TOPIC='Alarm Alert!'
Email_Address="abdul.basit.skipq@gmail.com"
Table='My_table_for_alarm_logs'
PERIOD = 1